# Generated by Django 5.0.14 on 2025-10-07 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Instagram username', max_length=255)),
                ('input_method', models.CharField(choices=[('manual', 'Manual Input'), ('scraped', 'URL Scraping')], help_text='How the data was collected', max_length=10)),
                ('follower_count', models.IntegerField(help_text='Number of followers')),
                ('following_count', models.IntegerField(help_text='Number of following')),
                ('post_count', models.IntegerField(help_text='Number of posts')),
                ('bio_length', models.IntegerField(help_text='Length of bio text')),
                ('has_profile_pic', models.BooleanField(help_text='Has profile picture')),
                ('has_external_url', models.BooleanField(help_text='Has external URL in bio')),
                ('avg_likes_per_post', models.FloatField(help_text='Average likes per post')),
                ('avg_comments_per_post', models.FloatField(help_text='Average comments per post')),
                ('follower_following_ratio', models.FloatField(help_text='Follower to following ratio')),
                ('engagement_rate', models.FloatField(help_text='Engagement rate percentage')),
                ('is_private', models.BooleanField(default=False, help_text='Is account private')),
                ('prediction', models.CharField(choices=[('Real', 'Real Account'), ('Fake', 'Fake Account')], help_text='Model prediction result', max_length=10)),
                ('confidence_score', models.FloatField(help_text='Prediction confidence (0-1)')),
                ('shap_explanation', models.JSONField(default=dict, help_text='Top features influencing prediction')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis History',
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
