# Generated by Django 5.0.14 on 2025-10-08 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('bio', models.TextField(blank=True, max_length=2200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='simulation/profiles/')),
                ('external_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='simulation/posts/')),
                ('caption', models.TextField(blank=True, max_length=2200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='detector.simulateduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='detector.simulatedpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_given', to='detector.simulateduser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField(default=0)),
                ('total_likes_given', models.IntegerField(default=0)),
                ('total_comments_given', models.IntegerField(default=0)),
                ('average_post_interval', models.FloatField(default=0.0)),
                ('average_like_interval', models.FloatField(default=0.0)),
                ('session_duration', models.FloatField(default=0.0)),
                ('bio_length', models.IntegerField(default=0)),
                ('has_profile_pic', models.BooleanField(default=False)),
                ('has_external_url', models.BooleanField(default=False)),
                ('username_entropy', models.FloatField(default=0.0)),
                ('avg_comment_length', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('calculated_follower_count', models.IntegerField(default=0)),
                ('calculated_following_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='detector.simulateduser')),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(choices=[('Real', 'Real Account'), ('Fake', 'Fake Account')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('features_snapshot', models.JSONField()),
                ('shap_values', models.JSONField()),
                ('top_features', models.JSONField()),
                ('is_latest', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='detector.simulateduser')),
            ],
            options={
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['user', 'is_latest'], name='detector_si_user_id_d7d440_idx'), models.Index(fields=['predicted_at'], name='detector_si_predict_c44254_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimulatedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='detector.simulatedpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='detector.simulateduser')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
