# Generated by Django 6.0.1 on 2026-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_simulateduser_simulatedpost_simulatedcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook')], default='instagram', help_text='Social media platform', max_length=20),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='profile_url',
            field=models.URLField(blank=True, help_text='Profile URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='username',
            field=models.CharField(help_text='Social media username', max_length=255),
        ),
        migrations.AddIndex(
            model_name='analysishistory',
            index=models.Index(fields=['platform', '-created_at'], name='detector_an_platfor_e5f9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysishistory',
            index=models.Index(fields=['username'], name='detector_an_usernam_a4d872_idx'),
        ),
    ]
